data:
  min_t: 0.01
  samples_per_eval_length: 4
  num_eval_lengths: 10
  num_t: 100

diffuser:
  diffuse_trans: True
  diffuse_rot: True
  r3:
    min_b: 0.1
    max_b: 20.0
    coordinate_scaling: 0.1
  so3:
    num_omega: 1000
    num_sigma: 1000
    min_sigma: 0.1
    max_sigma: 1.5
    schedule: logarithmic
    cache_dir: .cache/
    use_cached_score: False

model:
  node_embed_size: 256
  edge_embed_size: 128
  dropout: 0.0
  embed:
    index_embed_size: 32
    aatype_embed_size: 64
    embed_self_conditioning: True
    num_bins: 22
    min_bin: 1e-5
    max_bin: 20.0
  ipa:
    c_s: 256 # ${model.node_embed_size}
    c_z: 128 # ${model.edge_embed_size}
    c_hidden: 256
    c_skip: 64
    no_heads: 8
    no_qk_points: 8
    no_v_points: 12
    seq_tfmr_num_heads: 4
    seq_tfmr_num_layers: 2
    num_blocks: 4
    coordinate_scaling: 0.1 # ${diffuser.r3.coordinate_scaling}

experiment:
  trans_loss_weight: 1.0
  rot_loss_weight: 0.5
  rot_loss_t_threshold: 0.2
  separate_rot_loss: True
  trans_x0_threshold: 1.0
  coordinate_scaling: 0.1 # ${diffuser.r3.coordinate_scaling}
  bb_atom_loss_weight: 1.0
  bb_atom_loss_t_filter: 0.25
  dist_mat_loss_weight: 1.0
  dist_mat_loss_t_filter: 0.25
  aux_loss_weight: 0.25

inference:
  diffusion:
    num_t: 500
    noise_scale: 0.1
    min_t: 0.01